DEFAULT_ACTIVITY_PARAS = -0xffff
SHOW_ACTIVITY_STATUS_NAME = 0b0000_0001
SHOW_ACTIVITY_STATUS_DATE = 0b0000_0010
SHOW_ACTIVITY_STATUS_CONTENT = 0b0000_0100
BONUS_FLOW_TYPE_INCREASE = 0x0000
BONUS_FLOW_TYPE_DECREASE = 0x0001
BONUS_FLOW_TYPE_SET_TO = 0x0002

AUTO_BONUS_OPERATOR_REAL_NAME = "AUTO"
COMMON_ACCOUNT_REAL_NAME = "COMMON"
ADMIN_BONUS_OPERATOR_REAL_NAME = "ADMIN"

HELPER_COMMAND_ALL_CAN_USE = "所有人可用"
HELPER_COMMAND_ADMIN_CAN_USE ="俱乐部管理员可用"
HELPER_COMMAND_CALL_METHOD_DIRECT = "私聊可用"
HELPER_COMMAND_CALL_METHOD_GROUP = "俱乐部群聊可用"
HELPER_CLUB_GROUP_NAME ="XXX俱乐部"
HELPER_ACTIVITY_NAME = "XXX俱乐部_X月XX活动A"
HELPER_ACTIVITY_START_DATE = "2023-08-01"
HELPER_ACTIVITY_END_DATE = "2023-08-30"
HELPER_ACTIVITY_PLACE = "线上"
HELPER_ACTIVITY_PLANED_PEOPLE = "30"
HELPER_ACTIVITY_POINT_BUDGET = "300"
HELPER_ACTIVITY_POINT = "1"
HELPER_ACTIVITY_MAX_COUNT = "3"


